channels:
  - conda-forge
dependencies:
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - pytest
  - statsmodels
  - statannotations
  - pip:
    - "wheel>=0.46.2"
    - "urllib3>=2.5.0"
    - "setuptools>=78.1.1"